
var crudControllers=angular.module('crudControllers',[]);crudControllers.controller('gameController',['$scope','angularFireCollection','$rootScope',function($scope,angularFireCollection,$rootScope){var urlGames=new Firebase("https://wingaminglounge.firebaseio.com/wingaminglounge/games");$scope.games=angularFireCollection(urlGames);var id;$scope.typing=false;$scope.selectGame=function(game){console.log(game);$scope.limit=5;id=game.$id;ref=game.$ref;$scope.gameInfos=angular.fromJson(angular.toJson(game));$scope.gameInfos.$id=id;$scope.gameInfos.$ref=ref;$scope.typing=false;}
var isGameSaveClicked=false;$scope.saveGame=function(info){if(isGameSaveClicked){if($scope.selectGames==="New Game"){if($scope.gameInfos==""||$scope.gameInfos==null){console.log("game does not exist");}else{if($scope.gameInfos.gameSystem==""||$scope.gameInfos.gameSystem==null){console.log("No game system given");}else if($scope.gameInfos.gameTitle==""||$scope.gameInfos.gameTitle==null){console.log("No game title given");}else if($scope.gameInfos.gameArtUrl==""||$scope.gameInfos.gameArtUrl==null){console.log("No game art url given");}else if($scope.gameInfos.gameQuantity==""||$scope.gameInfos.gameQuantity==null){console.log("No game quantity given");}else{$scope.games.add($scope.gameInfos);console.log('new');}}
console.log('new game added');}else{$scope.games.update($scope.gameInfos);}
$("#add_game_btn").css({backgroundColor:"#17A9CC"}).html("Save");isGameSaveClicked=false;}else{$("#add_game_btn").css({backgroundColor:"#458B00"}).html("Are you sure?");isGameSaveClicked=true;}}
var isGameDeletedClicked=false;$scope.deleteGame=function(game){if(isGameDeletedClicked){$("#delete_game_btn").html("Delete");isGameDeletedClicked=false;$scope.games.remove(game.$id);}else{$("#delete_game_btn").html("Are you sure?");isGameDeletedClicked=true;}}}]);crudControllers.controller('stationController',['$scope','angularFireCollection','$rootScope','$location',function($scope,angularFireCollection,$rootScope,$location){var urlStations=new Firebase('https://wingaminglounge.firebaseio.com/wingaminglounge/stations');var urlEmptyStations=new Firebase('https://wingaminglounge.firebaseio.com/wingaminglounge/emptyStations')
$scope.stations=angularFireCollection(urlStations);$scope.emptyStations=angularFireCollection(urlEmptyStations);var isStationSaveClicked=false;$scope.saveStation=function(){if(isStationSaveClicked){if($scope.selectStations==="New Station")
{if($scope.stationInfos==""||$scope.stationInfos==null){console.log("Station does not exist");}else{if($scope.stationInfos.stationSystem==""||$scope.stationInfos.stationSystem==null){console.log("No SystemTV given");}else if($scope.stationInfos.stationTV==""||$scope.stationInfos.stationTV==null){console.log("Please enter a TV");}else if($scope.stationInfos.stationTVSerial==""||$scope.stationInfos.stationTVSerial==null){console.log("Please enter a TV Serial");}else{var stationsLength=$scope.stations.length+1;$scope.stationInfos.stationNumber=stationsLength;$scope.stations.add($scope.stationInfos);$scope.emptyStations.add({"stationNumber":stationsLength,"stationSystem":$scope.stationInfos.stationSystem});}}}else if(typeof $scope.selectStations!=='undefined'){$scope.stations.update($scope.stationInfos.$id);}
$("#save_station_btn").css({backgroundColor:"#17A9CC"}).html("Save");isStationSaveClicked=false;}else{$("#save_station_btn").css({backgroundColor:"#458B00"}).html("Are you sure?");isStationSaveClicked=true;}}
var isDeleteStationClicked=false;$scope.deleteStation=function(station){if(isDeleteStationClicked){$scope.stations.remove(station.$id);for(var i=0,max=$scope.emptyStations.length;i<max;i++){if($scope.emptyStations[i].stationNumber==station.stationNumber){$scope.emptyStations.remove($scope.emptyStations[i].$id);}}
$("#delete_station_btn").css({backgroundColor:"#ff0000"}).html("Delete");isDeleteStationClicked=false;}else{$("#delete_station_btn").css({backgroundColor:"#458B00"}).html("Are you sure?");isDeleteStationClicked=true;}}
$scope.stationInfo=function(info){$rootScope.stationInfos=$scope.stations[info];}}]);